In [1]:
import pandas as pd
import numpy as np
from collections import Counter

In [2]:
df = pd.read_csv("data/travel.csv")

print("Shape:", df.shape)
df.head()

Shape: (325, 16)

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
0,0,Northern,Delhi,Delhi,India Gate,War Memorial,1921,0.5,4.6,0,Yes,NaN,Historical,Yes,2.60,Evening
1,1,Northern,Delhi,Delhi,Humayun's Tomb,Tomb,1572,2.0,4.5,30,Yes,NaN,Historical,Yes,0.40,Afternoon
2,2,Northern,Delhi,Delhi,Akshardham Temple,Temple,2005,5.0,4.6,60,Yes,NaN,Religious,No,0.40,Afternoon
3,3,Northern,Delhi,Delhi,Waste to Wonder Park,Theme Park,2019,2.0,4.1,50,Yes,Monday,Environmental,Yes,0.27,Evening
4,4,Northern,Delhi,Delhi,Jantar Mantar,Observatory,1724,2.0,4.2,15,Yes,NaN,Scientific,Yes,0.31,Morning

In [3]:
df.info()
df.describe(include='all')

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 16 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        325 non-null    int64
 1   Zone                              325 non-null    str
 2   State                             325 non-null    str
 3   City                              325 non-null    str
 4   Name                              325 non-null    str
 5   Type                              325 non-null    str
 6   Establishment Year                325 non-null    str
 7   time needed to visit in hrs       325 non-null    float64
 8   Google review rating              325 non-null    float64
 9   Entrance Fee in INR               325 non-null    int64
 10  Airport with 50km Radius          325 non-null    str
 11  Weekly Off                        32 non-null     str
 12  Significance                      325 non-null    str
 13  DSLR Allowed                      325 non-null    str
 14  Number of google review in lakhs  325 non-null    float64
 15  Best Time to visit                325 non-null    str
dtypes: float64(3), int64(2), str(11)
memory usage: 40.8 KB

,Unnamed: 0,Zone,State,City,Name,Type,Establishment Year,time needed to visit in hrs,Google review rating,Entrance Fee in INR,Airport with 50km Radius,Weekly Off,Significance,DSLR Allowed,Number of google review in lakhs,Best Time to visit
count,325.000000,325,325,325,325,325,325,325.000000,325.000000,325.000000,325,32,325,325,325.000000,325
unique,NaN,6,33,214,321,78,162,NaN,NaN,NaN,2,5,25,2,NaN,7
top,NaN,Southern,Uttar Pradesh,Delhi,City Palace,Temple,Unknown,NaN,NaN,NaN,Yes,Monday,Historical,Yes,NaN,All
freq,NaN,98,23,16,2,59,111,NaN,NaN,NaN,227,23,78,265,NaN,164
mean,162.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.807692,4.486154,115.809231,NaN,NaN,NaN,NaN,0.408438,NaN
std,93.963645,NaN,NaN,NaN,NaN,NaN,NaN,0.971398,0.274580,530.859785,NaN,NaN,NaN,NaN,0.646668,NaN
min,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,0.500000,1.400000,0.000000,NaN,NaN,NaN,NaN,0.010000,NaN
25%,81.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,4.400000,0.000000,NaN,NaN,NaN,NaN,0.059000,NaN
50%,162.000000,NaN,NaN,NaN,NaN,NaN,NaN,1.500000,4.500000,0.000000,NaN,NaN,NaN,NaN,0.170000,NaN
75%,243.000000,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,4.600000,40.000000,NaN,NaN,NaN,NaN,0.500000,NaN
max,324.000000,NaN,NaN,NaN,NaN,NaN,NaN,7.000000,4.900000,7500.000000,NaN,NaN,NaN,NaN,7.400000,NaN

In [4]:
useful_cols = [
    "Zone",
    "State",
    "City",
    "Type",
    "Google review rating",
    "Best Time to visit",
    "time needed to visit in hrs",
    "Airport with 50km Radius"
]

df = df[useful_cols]

In [5]:
df.info()
df.head()

<class 'pandas.DataFrame'>
RangeIndex: 325 entries, 0 to 324
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Zone                         325 non-null    str
 1   State                        325 non-null    str
 2   City                         325 non-null    str
 3   Type                         325 non-null    str
 4   Google review rating         325 non-null    float64
 5   Best Time to visit           325 non-null    str
 6   time needed to visit in hrs  325 non-null    float64
 7   Airport with 50km Radius     325 non-null    str
dtypes: float64(2), str(6)
memory usage: 20.4 KB

,Zone,State,City,Type,Google review rating,Best Time to visit,time needed to visit in hrs,Airport with 50km Radius
0,Northern,Delhi,Delhi,War Memorial,4.6,Evening,0.5,Yes
1,Northern,Delhi,Delhi,Tomb,4.5,Afternoon,2.0,Yes
2,Northern,Delhi,Delhi,Temple,4.6,Afternoon,5.0,Yes
3,Northern,Delhi,Delhi,Theme Park,4.1,Evening,2.0,Yes
4,Northern,Delhi,Delhi,Observatory,4.2,Morning,2.0,Yes

In [6]:
df['City'] = df['City'].replace({
    'New Delhi': 'Delhi'
})
df.isnull().sum()

Zone                           0
State                          0
City                           0
Type                           0
Google review rating           0
Best Time to visit             0
time needed to visit in hrs    0
Airport with 50km Radius       0
dtype: int64

In [7]:
print(df['City'].unique())

<StringArray>
[        'Delhi',        'Mumbai',      'Lonavala',     'Bangalore',
     'Hyderabad',       'Kolkata',           'Goa',     'Ahmedabad',
        'Dwarka',      'Junagadh',
 ...
           'Diu',       'Deoghar',        'Ranchi',     'Bodh Gaya',
         'Patna',      'Gurugram',     'Kedarnath', 'Greater Noida',
     'Bengaluru',   'Cherrapunji']
Length: 213, dtype: str

In [8]:
df['City'] = df['City'].str.strip().str.title()
df['State'] = df['State'].str.strip().str.title()
df['Type'] = df['Type'].str.strip().str.title()
df['Zone'] = df['Zone'].str.strip().str.title()

In [9]:
unique_types = df['Type'].unique()
print("Unique Types:", unique_types)
print("Total unique types:", len(unique_types))

Unique Types: <StringArray>
[             'War Memorial',                      'Tomb',
                    'Temple',                'Theme Park',
               'Observatory',                    'Market',
                      'Fort',                  'Stepwell',
                      'Park',                    'Museum',
                       'Zoo',                  'Monument',
                   'Science',                 'Promenade',
             'National Park',          'Religious Shrine',
                     'Beach',            'Amusement Park',
                    'Palace',          'Botanical Garden',
       'Government Building',                  'Landmark',
                      'Lake',               'Film Studio',
                     'Tombs',                    'Bridge',
            'Cricket Ground',                      'Site',
                    'Church',                 'Waterfall',
            'Bird Sanctuary',                'Historical',
                  'Cultural', 'Urban Development Project',
        'Wildlife Sanctuary',                    'Shrine',
            'Religious Site',                  'Memorial',
           'Border Crossing',          'Sculpture Garden',
               'Scenic Area',                 'Viewpoint',
             'Mountain Peak',                      'Cave',
                 'Mausoleum',                  'Vineyard',
                    'Valley',                   'Temples',
          'Prehistoric Site',              'Scenic Point',
                 'Monastery',            'Tea Plantation',
           'Adventure Sport',                  'Trekking',
                 'Gurudwara',                'Ski Resort',
         'Suspension Bridge',                      'Ghat',
                   'Orchard',                'Confluence',
                      'Hill',              'Gravity Hill',
                   'Village',             'Sunrise Point',
                       'Dam',          'Spiritual Center',
                  'Aquarium',         'Religious Complex',
                    'Island',              'River Island',
             'Rock Carvings',                  'Township',
           'Natural Feature',             'Entertainment',
                      'Mall',        'Commercial Complex',
                    'Mosque',                'Race Track']
Length: 78, dtype: str
Total unique types: 78

In [10]:
type_mapping = {

    # Nature
    'Park': 'Nature',
    'National Park': 'Nature',
    'Wildlife Sanctuary': 'Nature',
    'Bird Sanctuary': 'Nature',
    'Botanical Garden': 'Nature',
    'Lake': 'Nature',
    'Waterfall': 'Nature',
    'Valley': 'Nature',
    'Hill': 'Nature',
    'Mountain Peak': 'Nature',
    'Scenic Area': 'Nature',
    'Scenic Point': 'Nature',
    'Viewpoint': 'Nature',
    'Island': 'Nature',
    'River Island': 'Nature',
    'Natural Feature': 'Nature',
    'Cave': 'Nature',
    'Dam': 'Nature',
    'Orchard': 'Nature',
    'Vineyard': 'Nature',
    'Tea Plantation': 'Nature',
    'Sunrise Point': 'Nature',
    'Gravity Hill': 'Nature',
    'Confluence': 'Nature',

    # Historical
    'Fort': 'Historical',
    'Palace': 'Historical',
    'Tomb': 'Historical',
    'Tombs': 'Historical',
    'Mausoleum': 'Historical',
    'War Memorial': 'Historical',
    'Memorial': 'Historical',
    'Monument': 'Historical',
    'Stepwell': 'Historical',
    'Prehistoric Site': 'Historical',
    'Rock Carvings': 'Historical',
    'Historical': 'Historical',
    'Border Crossing': 'Historical',

    # Religious
    'Temple': 'Religious',
    'Temples': 'Religious',
    'Church': 'Religious',
    'Mosque': 'Religious',
    'Gurudwara': 'Religious',
    'Monastery': 'Religious',
    'Shrine': 'Religious',
    'Religious Shrine': 'Religious',
    'Religious Site': 'Religious',
    'Religious Complex': 'Religious',
    'Spiritual Center': 'Religious',
    'Ghat': 'Religious',

    # Adventure
    'Adventure Sport': 'Adventure',
    'Trekking': 'Adventure',
    'Ski Resort': 'Adventure',
    'Suspension Bridge': 'Adventure',

    # Urban
    'Market': 'Urban',
    'Mall': 'Urban',
    'Commercial Complex': 'Urban',
    'Entertainment': 'Urban',
    'Theme Park': 'Urban',
    'Amusement Park': 'Urban',
    'Aquarium': 'Urban',
    'Zoo': 'Urban',
    'Cricket Ground': 'Urban',
    'Race Track': 'Urban',
    'Urban Development Project': 'Urban',

    # Mixed decisions
    'Museum': 'Historical',
    'Science': 'Historical',
    'Observatory': 'Historical',
    'Film Studio': 'Urban',
    'Landmark': 'Historical',
    'Sculpture Garden': 'Historical',
    'Government Building': 'Historical',
    'Township': 'Urban',
    'Village': 'Nature',
    'Promenade': 'Urban',
    'Bridge': 'Urban',
    'Site': 'Historical',
    'Beach':'Nature',
    'Cultural':'Historical'
}

In [11]:
df['Category'] = df['Type'].map(type_mapping)
print("Unmapped rows:", df['Category'].isnull().sum())

Unmapped rows: 0

In [12]:
category_index = {
    "Nature": 0,
    "Historical": 1,
    "Religious": 2,
    "Adventure": 3,
    "Urban": 4
}
df['Category_ID'] = df['Category'].map(category_index)
df[['Type', 'Category', 'Category_ID']].head(10)

           Type    Category  Category_ID
0  War Memorial  Historical            1
1          Tomb  Historical            1
2        Temple   Religious            2
3    Theme Park       Urban            4
4   Observatory  Historical            1
5        Market       Urban            4
6        Temple   Religious            2
7          Fort  Historical            1
8      Stepwell  Historical            1
9          Park      Nature            0

In [ ]:
print(df['Category_ID'].isnull().sum())

0

In [14]:
zone_vectors = pd.crosstab(df['Zone'], df['Category'])

# normalize
zone_vectors = zone_vectors.div(zone_vectors.sum(axis=1), axis=0)

zone_vectors.head()

Category       Adventure  Historical    Nature  Religious     Urban
Zone
Central          0.00000    0.384615  0.230769   0.256410  0.128205
Eastern          0.00000    0.177778  0.355556   0.355556  0.111111
North Eastern    0.00000    0.142857  0.571429   0.285714  0.000000
Northern         0.05618    0.280899  0.359551   0.235955  0.067416
Southern         0.00000    0.234694  0.459184   0.204082  0.102041

In [15]:
state_vectors = pd.crosstab(df['State'], df['Category'])

# normalize
state_vectors = state_vectors.div(state_vectors.sum(axis=1), axis=0)

state_vectors.head()

Category,Adventure,Historical,Nature,Religious,Urban
State,,,,,
Andaman And Nicobar Islands,0.0,0.250000,0.750000,0.000000,0.000000
Andhra Pradesh,0.0,0.277778,0.333333,0.277778,0.111111
Arunachal Pradesh,0.0,0.000000,0.000000,1.000000,0.000000
Assam,0.0,0.000000,0.625000,0.375000,0.000000
Bihar,0.0,0.000000,0.250000,0.500000,0.250000

In [16]:
cols = ['Nature', 'Historical', 'Religious', 'Adventure', 'Urban']

for col in cols:
    if col not in zone_vectors:
        zone_vectors[col] = 0
    if col not in state_vectors:
        state_vectors[col] = 0

In [17]:
zone_dict = zone_vectors.to_dict(orient='index')
state_dict = state_vectors.to_dict(orient='index')

In [18]:
import json

with open("data/zone_vectors.json", "w") as f:
    json.dump(zone_dict, f, indent=4)

with open("data/state_vectors.json", "w") as f:
    json.dump(state_dict, f, indent=4)

In [19]:
city_counts = pd.crosstab(df['City'], df['Category'])
for col in ['Nature', 'Historical', 'Religious', 'Adventure', 'Urban']:
    if col not in city_counts:
        city_counts[col] = 0
city_counts = city_counts.reset_index()
city_counts.head()

Category       City  Adventure  Historical  Nature  Religious  Urban
0          Agartala          0           1       0          0      0
1              Agra          0           2       0          0      0
2         Ahmedabad          0           2       1          0      2
3            Ajanta          0           0       1          0      0
4             Ajmer          0           0       0          1      0

In [20]:
cols = ['Nature', 'Historical', 'Religious', 'Adventure', 'Urban']

city_vectors = city_counts.copy()

city_vectors[cols] = city_vectors[cols].div(
    city_vectors[cols].sum(axis=1), axis=0
)

In [21]:
city_vectors.head()

Category       City  Adventure  Historical  Nature  Religious  Urban
0          Agartala        0.0         1.0     0.0        0.0    0.0
1              Agra        0.0         1.0     0.0        0.0    0.0
2         Ahmedabad        0.0         0.4     0.2        0.0    0.4
3            Ajanta        0.0         0.0     1.0        0.0    0.0
4             Ajmer        0.0         0.0     0.0        1.0    0.0

In [22]:
city_rating = df.groupby('City')['Google review rating'].mean().reset_index()

In [23]:
city_vectors = city_vectors.merge(city_rating, on='City')
city_vectors['rating_norm'] = (
    (city_vectors['Google review rating'] - 3) / 2
)

In [24]:
import json

city_dict = city_vectors.set_index('City').to_dict(orient='index')

with open("data/city_vectors.json", "w") as f:
    json.dump(city_dict, f, indent=4)

In [25]:
city_to_state = df.set_index('City')['State'].to_dict()

In [26]:
state_to_zone = df.set_index('State')['Zone'].to_dict()

In [27]:
import json

with open("data/city_to_state.json", "w") as f:
    json.dump(city_to_state, f, indent=4)

with open("data/state_to_zone.json", "w") as f:
    json.dump(state_to_zone, f, indent=4)